CC = gcc
CFLAGS = -Wno-int-conversion -g


all: exercise_one exercise_two


exercise_one: exercise_one.c
	$(CC) $(CFLAGS) exercise_one.c -o exercise_one


exercise_two: exercise_two.c
	$(CC) $(CFLAGS) exercise_two.c -o exercise_two


clean:
	rm -f exercise_one exercise_two